spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql/web20schdb?serverTimezone=UTC
    username: root
    password: omgd45945.+
    filters: wall,stat
    filter:
      stat:
        log-slow-sql: true
        slow-sql-millis: 1
        enabled: true
      wall:
        enabled: true
        config:
          drop-table-allow: false

    druid:
      aop-patterns: com.ren.web20.*

      stat-view-servlet:
        enabled: true
        login-username: 123test
        login-password: 123123
        reset-enable: false

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.ren.web20.pojo
